[project]
name = "finalpkms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "BrotherFab", email = "stewcollins17@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "openai>=2.8.1",
]

[project.scripts]
finalpkms = "finalpkms:main"

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"
